# vim: ts=2 sw=2 et

name: Manage Groups.io membership via YAML file
description: 'Use a YAML file in a repo to manage Groups.io subgroup membership'
author: 'Brian Warner (brianwarner)'
branding:
  icon: upload-cloud
  color: blue

on:
  push:
    branches:
      - master
    paths:
      - MAINTAINERS.yml # Make sure this path matches $MEMBERSHIP_FILE, below

jobs:
  sync_groupsio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install requests pyyaml
    - name: Sync MEMBERSHIP_FILE against Groups.io subgroups
      env:
        GROUPSIO_USERNAME: ${{ secrets.GROUPSIO_USERNAME }} # Set this up as defined in README.md
        GROUPSIO_PASSWORD: ${{ secrets.GROUPSIO_PASSWORD }} # Set this up as defined in README.md
        GROUP_NAME: yourgroupname # Find this as explained in README.md
        LIST_SUFFIX: '' # Optional, allows you to add a suffix to managed subgroups to keep organized
        UNIFIED_LIST: 'all-members' # Optional, adds all members to this meta list. Leave blank to disable.
        MEMBERSHIP_FILE: 'SAMPLE.yml' # Set this up as defined in README.md
        MAIN_LIST: 'main' # You probably don't need to change this, unless you used a custom main list name.
      run: python .github/workflows/sync-yaml-to-groupsio.py
